### Вовед во Биоинформатика

Изработила: Зорица Ников

Индекс: 216150

1. heart_failure_clinical_records_dataset.csv,
2. diabetes_binary_health_indicators_BRFSS2015.csv,
3. train_strokes.csv,
4. processed_cleveland_data.csv,
5. processed_hungarian_data.csv,
6. processed_switzerland_data.csv,
7. processed_va_data.csv,
8. MGE303_Term Project_Classification_Data (Disease).csv,

|                           |1|2|3|4|5|6|7|8|
|---------------------------|------------------------------------------|-----------------|-----------------|----------------------------|----------------------------|------------------------------|---------------------|-----------------------------------------------------|
|Size of dataset            |299                                       |70692            |43401            |302                         |293                         |122                           |199                  |21614                                                |
|Age                        |✅                                         |✅                |✅                |✅                           |✅                           |✅                             |✅                    |✅                                                    |
|Sex                        |✅                                         |✅                |✅                |✅                           |✅                           |✅                             |✅                    |✅                                                    |
|Chest Pain Type            |                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Systolic Blood Pressure    |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|Diastolic Blood Pressure   |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|Resting Blood Pressure     |                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Cholesterol                |                                          |✅                |                 |✅                           |✅                           |✅                             |✅                    |✅                                                    |
|Fasting Blood Sugar        |                                          |                 |✅                |✅                           |✅                           |✅                             |✅                    |✅                                                    |
|Resting ECG                |                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Maximum Heart Rate Achieved|                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Exercise Induced Angina    |                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Oldpeak                    |                                          |                 |                 |✅                           |✅                           |✅                             |✅                    |                                                     |
|Heart Disease              |                                          |✅                |✅                |✅                           |✅                           |✅                             |✅                    |✅                                                    |
|Hypertension               |✅                                         |✅                |✅                |                            |                            |                              |                     |✅                                                    |
|Ever Married               |                                          |                 |✅                |                            |                            |                              |                     |                                                     |
|Work Type                  |                                          |                 |✅                |                            |                            |                              |                     |                                                     |
|Residence Type             |                                          |                 |✅                |                            |                            |                              |                     |                                                     |
|Body Mass Index            |                                          |✅                |✅                |                            |                            |                              |                     |                                                     |
|Had a Stroke               |                                          |✅                |✅                |                            |                            |                              |                     |✅                                                    |
|Anaemia                    |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|CPK Enzyme Level           |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|Diabetes                   |✅                                         |✅                |                 |                            |                            |                              |                     |✅                                                    |
|Blood Ejection Fraction    |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|Platelets                  |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|Serum Creatinine           |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|Serum Sodium               |✅                                         |                 |                 |                            |                            |                              |                     |                                                     |
|Smoker                     |✅                                         |                 |✅                |                            |                            |                              |                     |✅                                                    |
|PhysActivity               |                                          |✅                |                 |                            |                            |                              |                     |✅                                                    |
|Fruits                     |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|Veggies                    |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|HvyAlcoholConsump          |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|GenHlth                    |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|MentHlth                   |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|PhysHlth                   |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|DiffWalk                   |                                          |✅                |                 |                            |                            |                              |                     |                                                     |
|Waist Circumference        |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|SGOT ASL                   |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|SGPT ALT                   |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|GAMMA GTP                  |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |
|Hemoglobin                 |                                          |                 |                 |                            |                            |                              |                     |✅                                                    |

### Imports

In [43]:
import pandas as pd

from random import randint

### Utility functions

In [44]:
def read_and_select_columns(file_path, selected_columns):
    data = pd.read_csv(file_path)
    
    # Check if the selected columns exist in the file
    missing_columns = [col for col in selected_columns if col not in data.columns]
    if missing_columns:
        raise ValueError(f"Missing columns in CSV file: {missing_columns}")
    
    return data[selected_columns]

In [45]:
files = [
    "heart_failure_clinical_records_dataset.csv",
    "diabetes_binary_health_indicators_BRFSS2015.csv",
    "train_strokes.csv",
    "processed_cleveland_data.csv",
    "processed_hungarian_data.csv",
    "processed_switzerland_data.csv",
    "processed_va_data.csv",
    "MGE303_Term Project_Classification_Data (Disease).csv"
]

select_columns = [
    ["age", "sex", "high_blood_pressure", "diabetes", "smoking"],
    ["Age", "Sex", "HighChol", "HeartDiseaseorAttack", "HighBP", "BMI", "Stroke", "Diabetes_binary", "PhysActivity"],
    ["age", "gender", "avg_glucose_level", "heart_disease", "hypertension", "bmi", "stroke", "smoking_status"],
    ["age", "sex", "cp", "trestbps", "chol", "fbs", "num"],
    ["age", "sex", "cp", "trestbps", "chol", "fbs", "num"],
    ["age", "sex", "cp", "trestbps", "chol", "fbs", "num"],
    ["age", "sex", "cp", "trestbps", "chol", "fbs", "num"],
    ["AGE", "gender", "BP_HIGH", "BP_LWST", "TOT_CHOLE", "BLDS", "H_HDISE_YN", "HY_YN", "H_APOP_YN", "H_DIABML_YN", "DSQTY", "EXER_M"]
]

In [46]:
filtered_datasets = [read_and_select_columns(f'./datasets/{files[i]}', select_columns[i]) for i in range(len(files))]

In [47]:
# Example
filtered_datasets[1]

,Age,Sex,HighChol,HeartDiseaseorAttack,HighBP,BMI,Stroke,Diabetes_binary,PhysActivity
0,9.0,0.0,1.0,0.0,1.0,40.0,0.0,0.0,0.0
1,7.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,1.0
2,9.0,0.0,1.0,0.0,1.0,28.0,0.0,0.0,0.0
3,11.0,0.0,0.0,0.0,1.0,27.0,0.0,0.0,1.0
4,11.0,0.0,1.0,0.0,1.0,24.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
253675,5.0,1.0,1.0,0.0,1.0,45.0,0.0,0.0,0.0
253676,11.0,0.0,1.0,0.0,1.0,18.0,0.0,1.0,0.0
253677,2.0,0.0,0.0,0.0,0.0,28.0,0.0,0.0,1.0
253678,7.0,1.0,0.0,0.0,1.0,23.0,0.0,0.0,0.0
253679,9.0,0.0,1.0,1.0,1.0,25.0,0.0,1.0,1.0

#### Process `heart_failure_clinical_records_dataset.csv`

In [48]:
filtered_datasets[0]

      age  sex  high_blood_pressure  diabetes  smoking
0    75.0    1                    1         0        0
1    55.0    1                    0         0        0
2    65.0    1                    0         0        1
3    50.0    1                    0         0        0
4    65.0    0                    0         1        0
..    ...  ...                  ...       ...      ...
294  62.0    1                    1         1        1
295  55.0    0                    0         0        0
296  45.0    0                    0         1        0
297  45.0    1                    0         0        1
298  50.0    1                    0         0        1

[299 rows x 5 columns]

In [49]:
p1 = {
    "Age": filtered_datasets[0]["age"],
    "Sex": filtered_datasets[0]["sex"].map(int),
    "Hypertension": filtered_datasets[0]["high_blood_pressure"],
    "Diabetes": filtered_datasets[0]["diabetes"],
    "Smoking": filtered_datasets[0]["smoking"]
}

#### Process `diabetes_binary_health_indicators_BRFSS2015.csv`

In [50]:
filtered_datasets[1]

,Age,Sex,HighChol,HeartDiseaseorAttack,HighBP,BMI,Stroke,Diabetes_binary,PhysActivity
0,9.0,0.0,1.0,0.0,1.0,40.0,0.0,0.0,0.0
1,7.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,1.0
2,9.0,0.0,1.0,0.0,1.0,28.0,0.0,0.0,0.0
3,11.0,0.0,0.0,0.0,1.0,27.0,0.0,0.0,1.0
4,11.0,0.0,1.0,0.0,1.0,24.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
253675,5.0,1.0,1.0,0.0,1.0,45.0,0.0,0.0,0.0
253676,11.0,0.0,1.0,0.0,1.0,18.0,0.0,1.0,0.0
253677,2.0,0.0,0.0,0.0,0.0,28.0,0.0,0.0,1.0
253678,7.0,1.0,0.0,0.0,1.0,23.0,0.0,0.0,0.0
253679,9.0,0.0,1.0,1.0,1.0,25.0,0.0,1.0,1.0

In [51]:
age_mapping = {
        1: (18, 24),
        2: (25, 29),
        3: (30, 34),
        4: (35, 39),
        5: (40, 44),
        6: (45, 49),
        7: (50, 54),
        8: (55, 59),
        9: (60, 64),
       10: (65, 69),
       11: (70, 74),
       12: (75, 79),
       13: (80, 100)
    }

In [52]:
p2 = {
    "Age": filtered_datasets[1]["Age"].map(int).map(lambda x : randint(age_mapping[x][0], age_mapping[x][1])),
    "Sex": filtered_datasets[1]["Sex"].map(int),
    "High Cholesterol": filtered_datasets[1]["HighChol"].map(int),
    "Heart Disease": filtered_datasets[1]["HeartDiseaseorAttack"].map(int),
    "Hypertension": filtered_datasets[1]["HighBP"].map(int),
    "BMI": filtered_datasets[1]["BMI"].map(int),
    "Stroke": filtered_datasets[1]["Stroke"].map(int),
    "Diabetes": filtered_datasets[1]["Diabetes_binary"].map(int),
    "Physical Activity": filtered_datasets[1]["PhysActivity"].map(int),
}

#### Process `train_strokes.csv`

In [53]:
filtered_datasets[2]

,age,gender,avg_glucose_level,heart_disease,hypertension,bmi,stroke,smoking_status
0,3.0,Male,95.12,0,0,18.0,0,NaN
1,58.0,Male,87.96,0,1,39.2,0,never smoked
2,8.0,Female,110.89,0,0,17.6,0,NaN
3,70.0,Female,69.04,0,0,35.9,0,formerly smoked
4,14.0,Male,161.28,0,0,19.1,0,NaN
...,...,...,...,...,...,...,...,...
43395,10.0,Female,58.64,0,0,20.4,0,never smoked
43396,56.0,Female,213.61,0,0,55.4,0,formerly smoked
43397,82.0,Female,91.94,0,1,28.9,0,formerly smoked
43398,40.0,Male,99.16,0,0,33.2,0,never smoked
43399,82.0,Female,79.48,0,0,20.6,0,never smoked

In [54]:
p3 = {
    "Age": filtered_datasets[2]["age"],
    "Sex": filtered_datasets[2]["gender"].map({ "Male" : 1, "Female": 0 }),
    "Fasting Blood Sugar": filtered_datasets[2]["avg_glucose_level"].map(lambda x : 1 if x >= 126 else 0),
    "Heart Disease": filtered_datasets[2]["heart_disease"],
    "Hypertension": filtered_datasets[2]["hypertension"],
    "BMI": filtered_datasets[2]["bmi"],
    "Stroke": filtered_datasets[2]["stroke"],
    "Smoking": filtered_datasets[2]["smoking_status"].map(lambda x : 1 if x == "smokes" else 0)
}

#### Process `processed_x_data.csv`

In [55]:
filtered_datasets[3]

     age  sex  cp  trestbps  chol  fbs  num
0     67    1   4       160   286    0    2
1     67    1   4       120   229    0    1
2     37    1   3       130   250    0    0
3     41    0   2       130   204    0    0
4     56    1   2       120   236    0    0
..   ...  ...  ..       ...   ...  ...  ...
297   45    1   1       110   264    0    1
298   68    1   4       144   193    1    2
299   57    1   4       130   131    0    3
300   57    0   2       130   236    0    1
301   38    1   3       138   175    0    0

[302 rows x 7 columns]

In [56]:
def process_x_datasets():
    results = []
    for i in range(3, 3 + 4):
        results.append({
            "Age": filtered_datasets[i]["age"],
            "Sex": filtered_datasets[i]["sex"],
            "Chest Pain Type": filtered_datasets[i]["cp"],
            "Hypertension": filtered_datasets[i]["trestbps"].map(lambda x : -1 if x == "?" else (1 if int(x) >= 140 else 0)),
            "High Cholesterol": filtered_datasets[i]["chol"].map(lambda x : -1 if x == "?" else (1 if int(x) >= 220 else 0)),
            "Fasting Blood Sugar": filtered_datasets[i]["fbs"].map(lambda x : -1 if x == "?" else int(x)),
            "Heart Disease": filtered_datasets[i]["num"].map(lambda x : 1 if int(x) > 1 else 0)
        })

    return results

#### Process `MGE303_Term Project_Classification_Data (Disease).csv`

In [57]:
filtered_datasets[7]

,AGE,gender,BP_HIGH,BP_LWST,TOT_CHOLE,BLDS,H_HDISE_YN,HY_YN,H_APOP_YN,H_DIABML_YN,DSQTY,EXER_M
0,66,1,120.0,70.0,199.0,87.0,0,1,0,0,0,Once a week
1,55,1,110.0,80.0,178.0,85.0,0,1,0,0,0,Never
2,54,0,117.0,76.0,195.0,92.0,0,1,0,0,0,Once a week
3,29,1,126.0,82.0,150.0,86.0,0,1,0,0,1,Once a week
4,43,1,130.0,85.0,134.0,104.0,0,1,0,0,2,Once a week
...,...,...,...,...,...,...,...,...,...,...,...,...
21608,36,1,130.0,80.0,185.0,79.0,0,0,0,0,0,Never
21609,31,0,102.0,68.0,164.0,94.0,0,0,0,0,0,Never
21610,42,1,118.0,76.0,192.0,96.0,0,0,0,0,2,Never
21611,34,0,106.0,66.0,190.0,83.0,0,0,0,0,0,Once a week
21612,51,0,110.0,77.0,196.0,82.0,0,0,0,0,1,Never

In [58]:
p4 = {
    "Age": filtered_datasets[7]["AGE"],
    "Sex": filtered_datasets[7]["gender"],
    "Fasting Blood Sugar": filtered_datasets[7]["BLDS"].map(lambda x : 1 if x >= 126 else 0),
    "High Cholesterol": filtered_datasets[7]["TOT_CHOLE"].map(lambda x : 1 if x >= 220 else 0),
    "Heart Disease": filtered_datasets[7]["H_HDISE_YN"],
    "Hypertension": filtered_datasets[7]["HY_YN"],
    "Stroke": filtered_datasets[7]["H_APOP_YN"],
    "Diabetes": filtered_datasets[7]["H_DIABML_YN"],
    "Smoking": filtered_datasets[7]["DSQTY"].map(lambda x : 1 if x > 0 else 0),
    "Physical Activity": filtered_datasets[7]["EXER_M"].map(lambda x : 0 if x == "Never" or x == "Once a week" else 1)
}

### Collect all dictionaries in one place

In [59]:
c = process_x_datasets()
dicts = [p1, p2, p3, c[0], c[1], c[2], c[3], p4]
dicts = [pd.DataFrame(x) for x in dicts]

In [60]:
dicts[7]

,Age,Sex,Fasting Blood Sugar,High Cholesterol,Heart Disease,Hypertension,Stroke,Diabetes,Smoking,Physical Activity
0,66,1,0,0,0,1,0,0,0,0
1,55,1,0,0,0,1,0,0,0,0
2,54,0,0,0,0,1,0,0,0,0
3,29,1,0,0,0,1,0,0,1,0
4,43,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
21608,36,1,0,0,0,0,0,0,0,0
21609,31,0,0,0,0,0,0,0,0,0
21610,42,1,0,0,0,0,0,0,1,0
21611,34,0,0,0,0,0,0,0,0,0
21612,51,0,0,0,0,0,0,0,1,0

### Combine all of the datasets into one big dataset

In [61]:
combined_df = pd.concat(dicts, axis=0, ignore_index=True).fillna(-1)

# Convert all float columns to ints
for col in combined_df.columns:
    if combined_df[col].dtype == 'float64':
        combined_df[col] = combined_df[col].astype('int')

In [62]:
combined_df

,Age,Sex,Hypertension,Diabetes,Smoking,High Cholesterol,Heart Disease,BMI,Stroke,Physical Activity,Fasting Blood Sugar,Chest Pain Type
0,75,1,1,0,0,-1,-1,-1,-1,-1,-1,-1
1,55,1,0,0,0,-1,-1,-1,-1,-1,-1,-1
2,65,1,0,0,1,-1,-1,-1,-1,-1,-1,-1
3,50,1,0,0,0,-1,-1,-1,-1,-1,-1,-1
4,65,0,0,1,0,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
319903,36,1,0,0,0,0,0,-1,0,0,0,-1
319904,31,0,0,0,0,0,0,-1,0,0,0,-1
319905,42,1,0,0,1,0,0,-1,0,0,0,-1
319906,34,0,0,0,0,0,0,-1,0,0,0,-1
319907,51,0,0,0,1,0,0,-1,0,0,0,-1

#### Save the dataset

In [63]:
combined_df.to_csv("./combined_dataset.csv", index=False)